name: custom_progress_button
description: Custom progress button help developers to build button with defferent states handling.
  it build with animation to handle each state change during run time
homepage: https://github.com/georgesamirmansour/custom_progress_button

version: 1.0.1

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
